# Generated by Django 3.1 on 2024-05-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230716_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size'), ('emirates', 'Emirates'), ('quantity', 'Quantity')], max_length=100),
        ),
    ]
