# Generated by Django 3.1 on 2024-05-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20240503_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('emirates', 'emirates'), ('quantity', 'quantity')], max_length=100),
        ),
    ]
